### ISSUE TITLE
Sending presence leave event times out whilst still connected

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-asset-tracking-android#862] opened 2022-12-23 14:57 UTC
When a delivery has completed, the publisher sends a presence leave event on the tracking channel and then detaches from the channel.

This is typically visible in the logs as “`zo0.b: leave();`” followed by “`io.ably.lib.transport.b: onMessage()`” with the returned ACK, for example:

```
18-12-22 19:59:07.702: zo0.b: leave(); channel = tracking:bo:22606154
18-12-22 19:59:07.702: zo0.b: update(); channel = tracking:bo:22606154
18-12-22 19:59:07.703: io.ably.lib.transport.WebSocketTransport: send(); action = presence
18-12-22 19:59:07.703: io.ably.lib.transport.WebSocketTransport: send(): presence: {"action":14,"channel":"tracking:bo:22606154","count":0,"flags":0,"msgSerial":339,"presence":[{"data":"{\"rawLocations\":false,\"type\":\"PUBLISHER\"}","action":3}],"timestamp":0}
18-12-22 19:59:07.923: io.ably.lib.transport.b: onMessage() ( ... ): ack: {"action":1,"count":1,"flags":0,"msgSerial":339,"timestamp":0}
```

From log redacted_08147607dc6202d1cb65ef57cdc42d53_error_session_639FA682023000012C9EE2B941CCBE13_DNE_1_v2.log however, the leave event was sent but no ACK was received:

```
18-12-22 19:48:58.570: zo0.b: leave(); channel = tracking:bo:22607777
18-12-22 19:48:58.571: zo0.b: update(); channel = tracking:bo:22607777
18-12-22 19:48:58.572: io.ably.lib.transport.WebSocketTransport: send(); action = presence
18-12-22 19:48:58.589: io.ably.lib.transport.WebSocketTransport: send(): presence: {"action":14,"channel":"tracking:bo:22607777","count":0,"flags":0,"msgSerial":1,"presence":[{"data":"{\"rawLocations\":false,\"type\":\"PUBLISHER\"}","action":3}],"timestamp":0}
18-12-22 19:49:27.032: [j] Publisher stop operation failed kotlinx.coroutines.c3: Timed out waiting for 30000 ms 	at kotlinx.coroutines.e3.a(Unknown Source:24) 	at kotlinx.coroutines.d3.run(Unknown Source:2) 	at kotlinx.coroutines.l1$b.run(Unknown Source:2) 	at kotlinx.coroutines.l1.s0(SourceFile:76) 	at kotlinx.coroutines.t0.run(SourceFile:43) 	at java.lang.Thread.run(Thread.java:923)
```

This resulted in a “Stopping Publisher Failed” exception:

```
PublisherStoppedError(message=Stopping Publisher Failed, cause=kotlinx.coroutines.c3: Timed out waiting for 30000 ms) 	at redacted.ably.PublisherService$h.invokeSuspend(SourceFile:67) 	at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:12) 	at kotlinx.coroutines.b1.run(SourceFile:105) 	at android.os.Handler.handleCallback(Handler.java:938) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:246) 	at android.app.ActivityThread.main(ActivityThread.java:8645) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) Caused by: kotlinx.coroutines.c3: Timed out waiting for 30000 ms 	at kotlinx.coroutines.e3.a(Unknown Source:24) 	at kotlinx.coroutines.d3.run(Unknown Source:2) 	at kotlinx.coroutines.l1$b.run(Unknown Source:2) 	at kotlinx.coroutines.l1.s0(SourceFile:76) 	at kotlinx.coroutines.t0.run(SourceFile:43) 	at java.lang.Thread.run(Thread.java:923)
```

Looking in the router logs, the client was connected at the time the presence leave event was sent (they were connected to ap-southeast-2 between 2022-12-18T23:48:41.067Z and 2022-12-18T23:49:56.073Z, the above logs are 4 hours behind UTC).

The SDK agent string was: `ably-java/1.2.20 ably-asset-tracking-android/1.5.1 android/30`

**Comment by lawrence-forooghian** [comment] 2022-12-26 11:40
@paddybyers do you have any thoughts on where we should begin in the investigation of this one? I can try reproducing on the Android side but it sounds like it could equally be a network-related issue.

**Comment by lawrence-forooghian** [comment] 2022-12-26 12:02
From reading the stack trace of the timeout exception, it’s not clear to me which codebase is throwing the underlying exception, but I’m guessing that it comes from [this call to `withTimeout` in AAT’s `StopWorker`](https://github.com/ably/ably-asset-tracking-android/blob/a103f605b2c00e5d98e82ed3dfe55b8a44fdc567/publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/StopWorker.kt#L24), given that the 30 second timeout mentioned in the logs matches the default timeout of [`Publisher#stop()`](https://github.com/ably/ably-asset-tracking-android/blob/a103f605b2c00e5d98e82ed3dfe55b8a44fdc567/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L128).

It would be good to understand the sequence of interactions with the AAT SDK that led to this exception. Until I have further information, I’ll assume that a trackable is being added using [`track(…)`](https://github.com/ably/ably-asset-tracking-android/blob/a103f605b2c00e5d98e82ed3dfe55b8a44fdc567/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L48) and then the publisher is being stopped using [`stop()`](https://github.com/ably/ably-asset-tracking-android/blob/a103f605b2c00e5d98e82ed3dfe55b8a44fdc567/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L128).

**Comment by lawrence-forooghian** [comment] 2022-12-26 12:55
I have not been able to reproduce this one. (I also tried removing the check in the publisher example app which prevents the user from stopping the publisher whilst it still has trackables – see 24f176aef19696fc49960a96542050411dc4707b – but that made no difference.)

@paddybyers do you have any suggestions on next steps for this one?

**Comment by lawrence-forooghian** [comment] 2022-12-26 13:01
Here's a video of my reproduction attempt:

https://user-images.githubusercontent.com/53756884/209551756-a445bde0-f1f7-442a-9b4e-82b25c0a08de.mov

**Comment by lawrence-forooghian** [comment] 2022-12-26 13:20
I'm going to see if I can get the example app to continuously start and stop a publisher, perhaps it's a very sporadic issue. I suspect I’ll still fail to reproduce, though.

**Comment by lawrence-forooghian** [comment] 2022-12-26 14:33
> I'm going to see if I can get the example app to continuously start and stop a publisher, perhaps it's a very sporadic issue. I suspect I’ll still fail to reproduce, though. There are probably many factors outside of my control that led to the issue.

Tried doing that – see f9df6bee54c74d17e209086df9be0ebea68d8c3c – no failures yet after 130 iterations.

**Comment by lawrence-forooghian** [comment] 2022-12-26 17:41
Popping a couple of messages here from [internal Slack thread](https://ably-real-time.slack.com/archives/C04H7971DK2/p1672065406973389)

From @mschristensen:

> is there anything we can do in the SDK to gracefully handle a missing ACK without an exception being thrown?

From me:

> Hi Mike, I’m not sure that we can. The exception is the result of the following decisions, I believe:
> 
> * Ably client library: Although not explicitly stated in [RTP10](https://sdk.ably.com/builds/ably/specification/main/features/#RTP10), we can infer from e.g. [RTP10d](https://sdk.ably.com/builds/ably/specification/main/features/#RTP10d) that the `RealtimePresence#leave` method is meant to wait for an `ACK` or `NACK` from Ably before returning.
> * Asset tracking library:
>     * The library communicates failures using exceptions.
>     * The `Publisher#stop(timeoutInMilliseconds:)` method is not meant to return until the `RealtimePresence#leave` call has completed. If the timeout elapses before this has occurred, then it will stop waiting for that call to complete.
>     * In the case of a timeout, we wish to be able to communicate to the caller that this timeout occurred and that the `leave` call may have not had its intended effect. We consider this to be an error and hence throw an exception to communicate it.
> 
> So, assuming we’re not planning to change the `ACK`-waiting behaviour of the client library, then our only options are for the asset tracking library to either stop considering a timeout to be an error, or to introduce some other non-exception way of communicating this error. I’m not sure either of these would be desirable.
> 
> The `Publisher#stop` method [does document that it will throw a ](https://github.com/ably/ably-asset-tracking-android/blob/a103f605b2c00e5d98e82ed3dfe55b8a44fdc567/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L125)`TimeoutCancellationException`[ in the case of a timeout](https://github.com/ably/ably-asset-tracking-android/blob/a103f605b2c00e5d98e82ed3dfe55b8a44fdc567/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L125). So I think it’s reasonable to expect application developers to be prepared to receive this exception and to handle it in their applications (which, from the description of [#862](https://github.com/ably/ably-asset-tracking-android/issues/862), it looks like they’re already doing).
> 
> From what I can tell so far, the behaviour of the asset tracking library seems like a reasonable one in response to an `ACK` not being received. I think what we need to understand is whether that is in fact what happened, and if so then why, and if not then why the SDK thinks that it did. It might also be the result of a transient network issue, in which case we could assess whether the behaviour of the asset tracking SDK and the the client library is adequate for recovering from that sort of situation.

**Comment by paddybyers** [comment] 2022-12-26 20:42
See https://sdk.ably.com/builds/ably/specification/main/features/#RTN7a

```
All `ProtocolMessage` `Presence` and `Message` objects sent to Ably expect either an `ACK` or `NACK` from Ably to confirm successful receipt and acceptance or failure respectively. For clarity, it is unnecessary to fail the publish operation of a message using a timer. Instead the client library can rely on: the realtime system will send an `ACK` or `NACK` when connected; the client library will fail all awaiting messages once `SUSPENDED` (see [RTN7c](https://sdk.ably.com/builds/ably/specification/main/features/#RTN7c)); upon reconnecting, the client will resend all message awaiting a response, and the realtime system in turn will respond with an `ACK` or `NACK` (see [RTN19a](https://sdk.ably.com/builds/ably/specification/main/features/#RTN19a))
```

So the assumption should be that the `leave()` event *will* complete, and AAT should not timeout preempting that completion. The completion of that operation (with associated error code) will tell AAT whether that operation, if it failed, is retriable or not. If AAT gives up waiting for the response, then it has no way of knowing what to do.

> The `Publisher#stop` method [does document that it will throw a ](https://github.com/ably/ably-asset-tracking-android/blob/a103f605b2c00e5d98e82ed3dfe55b8a44fdc567/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L125`TimeoutCancellationException` [in the case of a timeout](https://github.com/ably/ably-asset-tracking-android/blob/a103f605b2c00e5d98e82ed3dfe55b8a44fdc567/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L125). So I think it’s reasonable to expect application developers to be prepared to receive this exception and to handle it in their applications (which, from the description of https://github.com/ably/ably-asset-tracking-android/issues/862, it looks like they’re already doing).

Is this useful behaviour in the API? If the client calls `stop()`, and that fails, then what? Does it mean that the publisher is fine, and just failed to stop? Or is it broken? I'm not convinced that just timing out, giving up, and passing the error back to the caller is helpful. I don't think the caller can then know anything about the state of the publisher.

My suspicion in this case is that there is a deadlock or some other condition which is preventing the client from reading the `ACK` from the websocket. We know already that the websocket connection was intact for the duration of this sequence. I think it's very unlikely that realtime just failed to `ACK` the message, with no other sign of errors in the channel.

While waiting 30s for the `ACK` we ought to also have received a websocket ping.  Do those events get logged at `VERBOSE`? Why didn't we see that? If reading from the websocket was stalled for some reason, it would also explain the fact that we didn't see the ping.

So can we have a look and understand whether or not there's a way that the websocket client reader thread could get blocked?

To reproduce, I'd be looking to simulate random transport failures or other network problems (delays etc).

**Comment by lmars** [comment] 2022-12-27 01:59
I managed to simulate similar behaviour by modifying the "Stop Tracking" button in the publishing-example-app to call `publisher.stop()` (i.e. [here](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-example-app/src/main/java/com/ably/tracking/example/publisher/TrackableDetailsActivity.kt#L80)), and then doing the following in an emulator:

- Add a trackable
- After a minute or so, disconnect from the Internet
- 30s later, stop the publisher
- 30s later, the exception is raised

Here's the relevant logs:

```
27-12-22 01:27:43.352: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
27-12-22 01:27:58.400: io.ably.lib.transport.WebSocketTransport: onWebsocketPing()
...
27-12-22 01:28:29.261: [DefaultPublisher] Publisher stop operation started
27-12-22 01:28:29.414: io.ably.lib.realtime.Channel: leave(); channel = tracking:001
27-12-22 01:28:29.415: io.ably.lib.realtime.Channel: update(); channel = tracking:001
27-12-22 01:28:29.416: io.ably.lib.transport.WebSocketTransport: send(); action = presence
27-12-22 01:28:29.418: io.ably.lib.transport.WebSocketTransport: send(): presence: {"action":14,"channel":"tracking:001","count":0,"flags":0,"msgSerial":4,"presence":[{"data":"{\"rawLocations\":false,\"type\":\"PUBLISHER\"}","action":3}],"timestamp":0}
...
27-12-22 01:28:59.282: [DefaultPublisher] Publisher stop operation failed
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
```

Shortly after the exception is raised, the WebSocket connection closes:

```
27-12-22 01:29:13.198: io.ably.lib.transport.WebSocketTransport: onClose(): wsCode = 1006; wsReason = The connection was closed because the other endpoint did not respond with a pong in time. For more information check: https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection; remote = false
```

Now, the realtime heartbeat interval is 15s, so I can't say this is exactly what happened in the crash log in the issue description, since there the app remained connected for more than 15s after the last PING in the logs, but this does look very similar.

**Comment by paddybyers** [comment] 2022-12-27 10:31
But here you're simulating a failure to ack a presence leave by being disconnected, whereas the issue reported is that happening whilst still connected. Or are you allowing it to reconnect?

**Comment by lawrence-forooghian** [comment] 2022-12-27 11:34
Just for my understanding, what does it mean from the point of view of the server when we talk about a client being "connected"?

**Comment by mschristensen** [comment] 2022-12-27 12:52
I've been trying to match the client logs from the issue description `redacted_08147607dc6202d1cb65ef57cdc42d53_error_session_639FA682023000012C9EE2B941CCBE13_DNE_1_v2.log` with the realtime system logs from Athena using:

```
SELECT * FROM "ably_logs"."realtime"
WHERE env='production' AND dt='2022-12-18'
AND time>'2022-12-18T23:47:50' AND time<'2022-12-18T23:49:59'
AND region='ap-southeast-2'
AND scope_channel_id='tracking:bo:22607777'
AND scope_app_id='h-e4WQ'
order by time asc
LIMIT 1000
```

The enter presence event on L317 in the client logs:

```
308 | Mon Dec 19 2022 05:18:44 GMT+0530 (India Standard Time) | 18-12-22 19:48:44.178: io.ably.lib.transport.WebSocketTransport: send(): presence: {"action":14,"channel":"tracking:bo:22607777","count":0,"flags":0,"msgSerial":0,"presence":[{"data":"{\"rawLocations\":false,\"resolution\":{\"accuracy\":\"BALANCED\",\"desiredInterval\":5000,\"minimumDisplacement\":10.0},\"type\":\"PUBLISHER\"}","clientId":"bo-231977","action":2}],"timestamp":0}
```

... has a matching entry in the realtime system logs on L25:

```
"production","ap-southeast-2","i-050c834ac5c036764","core","core.8396.2","core","2022-12-18T23:48:44.929Z","trace","ChannelPresenceMaster.enter()","channelKey = h-e4WQ:tracking:bo:22607777; origin = 6100ACTvwBJ4M6; actionEntry = PresenceMessage {⏎   id: '_JXW4GnOOC:0:0'，⏎   channel: undefined，⏎   clientId: 'bo-231977'，⏎   connectionId: '_JXW4GnOOC'，⏎   data: '{'rawLocations':false，'resolution':{'accuracy':'BALANCED'，'desiredInterval':5000，'minimumDisplacement':10.0}，'type':'PUBLISHER'}'，⏎   encoding: undefined，⏎   extras: undefined，⏎   timestamp: 1671407324929，⏎   action: 2⏎ }","610TqXUBABJ4Ry","h-e4WQ","tracking:bo:22607777","","","","","","","core","production","ap-southeast-2","2022-12-18"
```

There is then a presence leave event on L342:

```
333 | Mon Dec 19 2022 05:18:59 GMT+0530 (India Standard Time) | 18-12-22 19:48:58.589: io.ably.lib.transport.WebSocketTransport: send(): presence: {"action":14,"channel":"tracking:bo:22607777","count":0,"flags":0,"msgSerial":1,"presence":[{"data":"{\"rawLocations\":false,\"type\":\"PUBLISHER\"}","action":3}],"timestamp":0}
```

... which has no matching entry in the realtime system logs until 23:49:41 on L39:

```
"production","ap-southeast-2","i-050c834ac5c036764","core","core.8396.2","core","2022-12-18T23:49:41.076Z","trace","ChannelPresenceMaster.leaveMembers()","channelKey = h-e4WQ:tracking:bo:22607777; leaveRes = [⏎   {⏎     member: PresenceMessage {⏎       id: undefined，⏎       channel: undefined，⏎       clientId: 'bo-231977'，⏎       connectionId: '_JXW4GnOOC'，⏎       data: '{'rawLocations':false，'resolution':{'accuracy':'BALANCED'，'desiredInterval':5000，'minimumDisplacement':10.0}，'type':'PUBLISHER'}'，⏎       encoding: undefined，⏎       extras: undefined，⏎       timestamp: 1671407381075，⏎       action: 3⏎     }，⏎     leaveErr: null⏎   }⏎ ]","610TqXUBABJ4Ry","h-e4WQ","tracking:bo:22607777","","","","","","","core","production","ap-southeast-2","2022-12-18"
```

So, could it be that the problem isn't with the SDK not picking up an ACK but actually delaying sending of the actual presence leave message on the wire for some reason, which then times out?

**Comment by lmars** [comment] 2022-12-27 13:12
@paddybyers

> But here you're simulating a failure to ack a presence leave by being disconnected, whereas the issue reported is that happening whilst still connected

Taking a closer look at the sequence of events from the exception reported in the description (i.e. channel `tracking:bo:22607777`), here's what happened (all times UTC on 18-12-2022):

- 23:48:55: the last `onWebsocketPing()` line appears in the app log
- 23:48:56: the publisher is stopped
- 23:48:58: the app tries to leave presence
- 23:49:27: the 30s timeout exception is raised
- 23:49:41: the presence LEAVE event appears in presence history
- 23:49:56: the connection is closed in the router log

So this seems to suggest that there is a 60s window between the last successful PING and the connection being closed.

I re-ran my test above just now, and here's what I see:

- 12:40:37: the last `onWebsocketPing()` line appears in the app log
- 12:40:45: I disconnected from the Internet
- 12:40:52: I stopped the publisher
- 12:40:52: the app tries to leave presence
- 12:41:21: the presence LEAVE event appears in presence history
- 12:41:22: the 30s timeout exception is raised
- 12:41:36: the connection is closed in the router log

Which seems to confirm the 60s window, and if the publisher is stopped in the first 30s of that window, the operation will timeout before the connection is closed.

@lawrence-forooghian 

> what does it mean from the point of view of the server when we talk about a client being "connected"?

Based on my analysis above, I think "connected" above means "successfully responded to a PING in the last 60 seconds".

@mschristensen 

> There is then a presence leave event on L342: ... which has no matching entry in the realtime system logs until 23:49:41 on L39 .. could it be that the problem isn't with the SDK not picking up an ACK but actually delaying sending of the actual presence leave message on the wire for some reason, which then times out?

I think yes, we can conclude that this presence event was logged by the app but never actually made it to the realtime system, likely due to network issues.

**Comment by lmars** [comment] 2022-12-27 13:28
And my opinion on a fix, I think the `stop()` operation needs to just wait either for the ACK of the LEAVE event to be received, or for the connection to become disconnected (at which point it knows it's no longer present since it's not even connected), a 30s timeout doesn't seem to serve any purpose.

**Comment by lawrence-forooghian** [comment] 2022-12-27 13:57
Thanks for the above analysis @mschristensen and @lmars. I think it makes sense.

I had been looking into @paddybyers’s question about whether it was possible for some internal cause to prevent the library from receiving WebSocket data. It might be better for me to switch to thinking about Lewis‘s proposed solution.

And as for why we didn’t see any WebSocket pings, that could be explained by the same network issues that we imagine might have caused the presence leave event from reaching Realtime, right?

**Comment by lawrence-forooghian** [comment] 2022-12-27 13:59
For future debugging, I wonder whether we might also benefit from also adding logging _after_ the client library successfully sends a WebSocket message?

**Comment by lawrence-forooghian** [comment] 2022-12-27 14:29
@lmars I think I'm not familiar enough with this part of the client lib behaviour to understand this:

> or for the connection to become disconnected (at which point it knows it's no longer present since it's not even connected)

From reading https://ably.com/docs/realtime/presence#unstable-connections, my understanding is that a client can remain present on a channel even after the connection has moved to the `DISCONNECTED` state:

> Clients that are part of a presence set remain present for 15 seconds after they are abruptly disconnected, for example where the internet connection suddenly drops or the client is changing networks.

I'm almost certainly misunderstanding something, though.

Would you mind explaining your comment above, please?

**Comment by lawrence-forooghian** [comment] 2022-12-27 14:39
Another thing on that same page also suggests that entering the `DISCONNECTED` state doesn't necessarily imply you're immediately no longer present:

> Alternatively, if a member’s connection is abruptly disconnected and they do not resume their connection within a minute, Ably treats this as a leave event as the client is no longer present

**Comment by lmars** [comment] 2022-12-27 15:08
> as for why we didn’t see any WebSocket pings, that could be explained by the same network issues that we imagine might have prevented the presence leave event from reaching Realtime, right?

I think so, yes.

> I wonder whether we might also benefit from also adding logging after the client library successfully sends a WebSocket message?

That might be useful yes, I think that would be an ably-java thing, can you open a separate issue for that?

> > or for the connection to become disconnected (at which point it knows it's no longer present since it's not even connected)
>
> From reading https://ably.com/docs/realtime/presence#unstable-connections, my understanding is that a client can remain present on a channel even after the connection has moved to the DISCONNECTED state

Sure, but the aim here is for the client to leave presence _eventually_, which it can do in one of two ways, either successfully send a LEAVE event, or remain disconnected and have the realtime system emit the LEAVE event on behalf of the client, whereas currently the app is not handling the latter as a way to consider the publisher as stopped (instead raising an exception, which the calling code can't really do anything about).

So, if `publisher.stop()` is called, and then 30s later the connection closes, then it's really job done, all the app needs to do is make sure it doesn't try to re-enter presence if the connection re-establishes.

**Comment by lawrence-forooghian** [comment] 2022-12-27 16:27
So that'd mean that under your suggested behaviour, a successfully-completed call to `stop` wouldn't necessarily imply that the client is no longer in the presence set on the server – however it is a guarantee that the client will no longer be in the presence set on the server within some fixed amount of time?

**Comment by lmars** [comment] 2022-12-27 18:07
> a successfully-completed call to stop wouldn't necessarily imply that the client is no longer in the presence set on the server – however it is a guarantee that the client will no longer be in the presence set on the server within some fixed amount of time?

Pretty much, yeh.

I mean, if we really want that guarantee, we could just wait another 15s after seeing the DISCONNECTED event (and no subsequent CONNECTED event) and assume from that that the client has successfully left the channel, but I don't think that guarantee is really needed (i.e. just knowing that the publisher is disconnected and won't try to re-enter the channel in the future is enough).

Looking at the implementation, I think this timeout is just at the wrong level. It currently wraps a call to [`ably.close()`](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/StopWorker.kt#L33-L41) and is then [re-raised](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/StopWorker.kt#L45), but it should probably be a timeout just on [disconnecting from each channel](https://github.com/ably/ably-asset-tracking-android/blob/main/common/src/main/java/com/ably/tracking/common/Ably.kt#L442-L447) which is subsequently logged and ignored before then closing the connection.

**Comment by lawrence-forooghian** [comment] 2022-12-27 18:23
Something else I wanted to check was whether the subscriber app was correctly handling the synthesized `LEAVE` messages. I had assumed that these messages would contain no `data`, which would cause a problem for the subscriber apps, but upon testing it out, it seems like these synthesized `LEAVE` messages actually do include data – looks like they use the last presence data published for that member.

Is that a documented behaviour that we can rely on?

**Comment by paddybyers** [comment] 2022-12-27 21:13
> what does it mean from the point of view of the server when we talk about a client being "connected"?

If a client is connected, it means that there is an established transport between the client and the server. Both the client and server verify the ongoing liveness of that transport connection, by heartbeats or websocket ping frames. So from the POV of the server, it knows that a transport exists, and it has recently responded to a ping.

**Comment by paddybyers** [comment] 2022-12-27 21:19
When a transport drops, the client moves to the `DISCONNECTED` state, and the server puts the connection into the `dormant` state. If it remains dormant for 15s, there will be a synthesised `leave` event generated by the server. If the client succeeds in establishing a new transport, the server will put the connection back into the `connected` state.

So if a client loses connectivity and is unable to reestablish it, it will leave presence.

**Comment by paddybyers** [comment] 2022-12-27 21:20
> upon testing it out, it seems like these synthesized LEAVE messages actually do include data – looks like they use the last presence data published for that member.
> 
> Is that a documented behaviour that we can rely on?

Yes

**Comment by lawrence-forooghian** [comment] 2022-12-28 13:08
> > upon testing it out, it seems like these synthesized LEAVE messages actually do include data – looks like they use the last presence data published for that member.
> > Is that a documented behaviour that we can rely on?
> 
> Yes

Do you have a link to some documentation that I add as a comment in the code?

**Comment by paddybyers** [comment] 2022-12-28 22:21
> Do you have a link to some documentation that I add as a comment in the code?

No, I can't find one :) But that's definitely the intended behaviour and the implemented behaviour.

**Comment by lawrence-forooghian** [comment] 2022-12-29 00:01
OK, I'll refer to your above comment in the code, then. But, as a general point, and please let me know if you disagree, I think that we should be aiming for the Asset Tracking SDKs to serve as great example code for how to use the Ably client libraries. I think that in relying on behaviour that isn't publicly documented we might be falling a bit short of this aim.

**Comment by lawrence-forooghian** [comment] 2022-12-29 01:00
> > I wonder whether we might also benefit from also adding logging after the client library successfully sends a WebSocket message?
> 
> That might be useful yes, I think that would be an ably-java thing, can you open a separate issue for that?

Yup, I've opened https://github.com/ably/ably-java/issues/882 👍

**Comment by lawrence-forooghian** [comment] 2023-01-03 13:39
Ive opened #874 which removes the `TimeoutCancellationException` from `Publisher.stop` and describes how this will affect subscribers. I'd appreciate a review from either @paddybyers or @lmars given your deeper knowledge than me of the Realtime backend and client library behaviours.

**Closed** 2023-01-10 12:19 UTC
Labels: important
