### ISSUE TITLE
apps: Don't use toasts when a modal dialog would be more appropriate

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#34] opened 2020-11-26 11:16 UTC
Currently I'm looking at a line that reads:

```kotlin
showToast("Insert tracking ID")
```

Which is executed when the user has clicked the button in the app to start tracking but hasn't filled in required information.

A dialog that remains on screen until a button acknowledging the user has read it would be better. i.e. a classic alert.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-811) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment] 2022-07-05 07:27
I'm closing this issue as it's a duplicate of https://github.com/ably/ably-asset-tracking-android/issues/500

**Closed by KacperKluka** 2022-07-05 07:27 UTC
Labels: example-app
