### ISSUE TITLE
Unable to add publishing sdk to the projects with existing mapbox navigation 

### ISSUE THREAD

**Issue by chitho87** [ably/ably-asset-tracking-android#735] opened 2022-08-12 03:13 UTC
Error at compiling time says duplicate class "com.mapbox.module.Mapbox_TripNotificationModuleConfiguration".
Both existing Mapbox navigation SDK and the customized notification module from publishing SDK generate the same files.
My temporary solution is to disable the customized notification module from publishing SDK, then change the method startTripSession(withForegroundService = false), then rebuild to get an .aar file  to integrate Publishing SDK  with project already uses Mapbox navigation sdk. Everything seems to be fine.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2539) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment] 2022-08-12 07:47
Thank you for reporting this issue :bow: I'm glad to hear that you've found a workaround and this is not blocking your work :+1: 

It would be very helpful to get some more information to fix this issue on our side. Could you please share which Mapbox dependencies your application uses? And are you using a [custom notification for the Mapbox Navigation SDK](https://docs.mapbox.com/android/navigation/guides/ui-components/notifications/#custom-system-notifications) in your app?

**Comment by chitho87** [comment] 2022-08-13 11:10
Hi, I'm using the navigation SDK dependency: "com.mapbox.navigation:android:2,6,0". I did try the version "v2.7.0-rc.1" (the same one with the publishing SDK) but the compiling error still happened.
No, I don't use a custom notification for the Mapbox navigation SDK, but I believe the built-in module does generate this class "com.mapbox.module.Mapbox_TripNotificationModuleConfiguration".

**Comment by KacperKluka** [comment] 2022-08-18 12:31
Thank you for the information and sorry for the delay :bow: We are able to reproduce the issue and are working on a fix.

**Comment by chitho87** [comment] 2022-08-19 02:23
Sounds great, thanks

**Comment by KacperKluka** [comment] 2022-08-31 07:42
@chitho87 thank you for your patience and sorry for the delay :bow: We've been consulting this issue with Mapbox to make sure that we provide you with the best possible help.

Unfortunately, [only one instance of the Mapbox Nav SDK can be created per application](https://docs.mapbox.com/android/navigation/api/2.7.0/libnavigation-core/com.mapbox.navigation.core/-mapbox-navigation/?query=class%20MapboxNavigation). Therefore using Mapbox Nav SDK and AAT SDK together introduces some limitations. But it is possible to have them together, the downside is that you have to use AAT's `MapboxNavigation` configuration for the Nav SDK. This means that you won't be able to configure your Mapbox instance and you'll have to rely on our configuration.

**How to make it work:**
In the `build.gradle` you have to exclude the notification module from your Mapbox Nav SDK dependency:
```gradle
// The Ably Asset Tracking Publisher SDK for Android.
implementation ('com.ably.tracking:publishing-sdk:1.2.0')
                                                                  
// The Mapbox Navigation SDK.
implementation ('com.mapbox.navigation:android:2.6.0') {
    exclude group: "com.mapbox.navigation", module: "notification"
}
```

In the code you have to first start a publisher and then use the `MapboxNavigationProvider` to retrieve the Nav SDK instance the publisher has created:
```kotlin
val publisher = Publisher.publishers()
    // add publisher configuration
    .start()

val mapboxNavigation = MapboxNavigationProvider.retrieve()
mapboxNavigation.startTripSession()
```

Please let me know if this helps :bow:

**Comment by chitho87** [comment] 2022-08-31 08:26
Hi @KacperKluka, I've just checked it out and the bug is fixed! yay!!!
And I do realize the limitation of one instance for Mapbox Nav in the app (gotta be careful when call stopTripSession() while using navigation or else the tracking will stop).
Thank you for your support.

**Comment by KacperKluka** [comment] 2022-08-31 08:43
Great to hear that it solved your problem :hugs: I want to thank you for flagging this issue, thanks to you we added [a new section to our README](https://github.com/ably/ably-asset-tracking-android#using-aat-together-with-mapbox-navigation-sdk) that should help others with the same problem :bow: 

As the issue seems to be resolved I'm going to close it. If you'll need more support let me know and we'll reopen the issue :wink:

**Closed by KacperKluka** 2022-08-31 08:43 UTC
Labels: bug
